# Generated by Django 2.0.5 on 2018-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_de_blog',
            name='page_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug de la Página'),
        ),
    ]
