# Generated by Django 2.0.5 on 2018-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entrada_de_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_de_blog',
            name='categories',
            field=models.ManyToManyField(related_name='get_blogs', to='blog.Entrada_de_blog_category', verbose_name='Categorias'),
        ),
    ]
