# Generated by Django 2.0.5 on 2018-08-08 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_entrada_de_blog_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada_de_blog',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
