# Generated by Django 2.0.5 on 2018-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_productora',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_software',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lugar'),
        ),
    ]
