# Generated by Django 2.0.5 on 2018-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180608_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail_productora',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Productora'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail_software',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Software'),
        ),
    ]
