# Generated by Django 2.0.5 on 2018-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180608_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Video ID'),
        ),
    ]
