# Generated by Django 2.0.5 on 2018-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'catergorias',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='portfolio.ProjectCategory', verbose_name='Categoria'),
        ),
    ]
