# Generated by Django 2.0.5 on 2018-06-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180609_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
