# Generated by Django 2.0.5 on 2018-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180611_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='get_projects', to='portfolio.ProjectCategory', verbose_name='Categoria'),
        ),
    ]
