# Generated by Django 2.0.5 on 2018-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_menu', models.CharField(max_length=200, verbose_name='Título Menú')),
                ('title_header', models.CharField(max_length=200, verbose_name='Título Header')),
                ('subtitle_header', models.CharField(max_length=200, verbose_name='Subtítulo Header')),
                ('button', models.CharField(max_length=200, verbose_name='Botón Header')),
                ('title_service', models.CharField(max_length=200, verbose_name='Título Service')),
                ('title_portfolio', models.CharField(max_length=200, verbose_name='Título Porfolio')),
                ('title_cv', models.CharField(max_length=200, verbose_name='Título Sección CV')),
                ('url_cv', models.URLField(verbose_name='URL CV')),
                ('title_contact', models.CharField(max_length=200, verbose_name='Título Contact')),
                ('text_contact', models.TextField(verbose_name='Texto Contact')),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=200, verbose_name='Título Header')),
            ],
        ),
    ]
