# Generated by Django 2.0.5 on 2018-06-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizacion',
            options={'verbose_name': 'Personalización Front-end', 'verbose_name_plural': 'Personalizaciones'},
        ),
    ]
