# Generated by Django 2.0.5 on 2018-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180620_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='menu4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título Menú 4 '),
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='menu5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título Menú 5 '),
        ),
    ]
