# Generated by Django 2.0.5 on 2018-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180620_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='text_blog',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Text Blog'),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='title_blog',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título Blog'),
        ),
    ]
