# Generated by Django 2.0.5 on 2018-08-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180808_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Servicio')),
                ('text', models.CharField(max_length=200, verbose_name='Texto del Servicio')),
                ('icon', models.CharField(max_length=200, verbose_name='Icono del Servicio')),
            ],
        ),
    ]
